# Generated by Django 3.1.6 on 2021-02-11 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import helpdesk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=django.utils.crypto.get_random_string, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En espera'), ('ongoing', 'En curso'), ('closed', 'Cerrado')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('front', 'Frontline'), ('back', 'Back-office'), ('wfm', 'Workforce'), ('it', 'IT'), ('management', 'Management')], max_length=20)),
                ('category', models.CharField(choices=[('reunion', 'Sala de Reuniones'), ('ot', 'OT'), ('vto', 'VTO'), ('vacations', 'Vacaciones'), ('medic', 'Cita Médica'), ('insurance', 'Cita Aseguradora')], max_length=20)),
                ('is_escalated', models.BooleanField(default=False, help_text='Marcarlo sólo si este issue ya fue atendido previamente.', verbose_name='es escalado')),
                ('subject', models.CharField(help_text='Escribe un título.', max_length=200)),
                ('description', models.TextField(help_text='Describe cuál es el problema.')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='helpdesk.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Escribe aquí tu mensaje.', verbose_name='content')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=helpdesk.models.attachments_upload_url)),
                ('file', models.FileField(blank=True, upload_to=helpdesk.models.attachments_upload_url)),
                ('description', models.TextField(help_text='Describe el propósito de la imagen.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.ticket')),
            ],
        ),
    ]
