# Generated by Django 3.1.6 on 2021-02-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VacationRequest',
        ),
    ]
