# Generated by Django 3.1.6 on 2021-02-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_vacation_vacationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
