# Generated by Django 3.1.6 on 2021-02-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20210217_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket', verbose_name='vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='¡Vacaciones! Bien merecidas, {self.owner}', max_length=300),
        ),
    ]
