# Generated by Django 3.1.6 on 2021-02-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20210211_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
