# Generated by Django 3.1.6 on 2021-02-17 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20210217_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='from_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='to_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='to'),
        ),
    ]
