# Generated by Django 3.1.6 on 2021-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20210211_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='Que disfrutes tu tiempo offline :)', max_length=300),
        ),
    ]
