# Generated by Django 3.1.6 on 2021-02-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20210217_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='from_date',
            field=models.DateField(verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='Que disfrutes tu tiempo offline :)', max_length=300),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='helpdesk.ticket'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='to_date',
            field=models.DateField(verbose_name='to'),
        ),
    ]
