# Generated by Django 3.1.6 on 2021-02-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_auto_20210217_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='Te vamos a extrañar, {self.owner}. Disfruta tu tiempo offline :)', max_length=300),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='ticket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='helpdesk.ticket'),
        ),
    ]
