# Generated by Django 3.1.6 on 2021-02-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
    ]
