# Generated by Django 3.1.6 on 2021-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210213_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
