# Generated by Django 3.1.6 on 2021-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='Este es mi primer empleo en una compañía tan genial como Helpdesk.', max_length=90),
        ),
    ]
